// DO NOT EDIT: Code generated by matcha from nav.matcha

import gleam/string_tree.{type StringTree}

pub fn render_tree() -> StringTree {
  let tree = string_tree.from_string("")
  let tree =
    string_tree.append(
      tree,
      "<nav>
  <ul>
    <li><strong>Task App</strong></li>
  </ul>
  <ul>
    <li><a href=\"/\">Tasks</a></li>
    <li><a href=\"/projects\">Projects</a></li>
  </ul>
</nav>

",
    )

  tree
}

pub fn render() -> String {
  string_tree.to_string(render_tree())
}
