// DO NOT EDIT: Code generated by matcha from scripts.matcha

import gleam/string_tree.{type StringTree}



pub fn render_tree() -> StringTree {
    let tree = string_tree.from_string("")
    let tree = string_tree.append(tree, "<script src=\"https://unpkg.com/htmx.org@2.0.3\"></script>
<script src=\"https://unpkg.com/lucide@latest\"></script>
<script>lucide.createIcons();</script>

")

    tree
}

pub fn render() -> String {
    string_tree.to_string(render_tree())
}

