// DO NOT EDIT: Code generated by matcha from chat_header.matcha

import gleam/string_tree.{type StringTree}

pub fn render_tree(
  status status: String,
  leave_button leave_button: String,
) -> StringTree {
  let tree = string_tree.from_string("")
  let tree =
    string_tree.append(
      tree,
      "<div class=\"header\">
    <div class=\"header-content\">
        <h1>💬 Dream WebSocket Chat</h1>
        <div class=\"status\" id=\"status\">",
    )
  let tree = string_tree.append(tree, status)
  let tree =
    string_tree.append(
      tree,
      "</div>
    </div>
    ",
    )
  let tree = string_tree.append(tree, leave_button)
  let tree =
    string_tree.append(
      tree,
      "
</div>

",
    )

  tree
}

pub fn render(
  status status: String,
  leave_button leave_button: String,
) -> String {
  string_tree.to_string(render_tree(status: status, leave_button: leave_button))
}
