// DO NOT EDIT: Code generated by matcha from messages_container.matcha

import gleam/string_tree.{type StringTree}

pub fn render_tree() -> StringTree {
  let tree = string_tree.from_string("")
  let tree =
    string_tree.append(
      tree,
      "<div class=\"messages\" id=\"messages\"></div>

",
    )

  tree
}

pub fn render() -> String {
  string_tree.to_string(render_tree())
}
